### ISSUE TITLE
Part 1 feedback

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/MeganBeaudry-Project2#1]
For knitting, your file should be an Rmd file, not an R file. The data loading lines don't work/knit (even after I renamed it to Rmd) and you are setting a path to your local directory which doesn't work on my computer. That means I can't load the data. I therefore can't tell if it contains the information needed to answer your questions, so I unfortunately can't give you feedback on project feasibility.

**Comment by MeganSarah** [comment]
Hi Dr. Handel,

I am sorry that I posted the wrong file. A Rmd file has now been posted. In this file, the data is downloaded from github (a csv file from the raw data folder). 

Thank you,
Megan

**Comment by andreashandel** [comment]
something doesn't work, when i try to open the new Rmd file I only see gibberish. Not sure what is going wrong.
